import { Workout } from '../types';

export const YOUTUBE_VIDEOS: Workout[] = [
    // Daily Routine (20+ videos)
    { id: 'dr1', title: '10-Minute Morning Yoga', category: 'Daily Routine', videoId: '4C-gxOE0j7s', thumbnail: 'https://i.ytimg.com/vi/4C-gxOE0j7s/hqdefault.jpg', duration: '10 min'},
    { id: 'dr2', title: '10 min Morning Workout (No Jumping)', category: 'Daily Routine', videoId: 'M0uO8X3_tEA', thumbnail: 'https://i.ytimg.com/vi/M0uO8X3_tEA/hqdefault.jpg', duration: '10 min'},
    { id: 'dr3', title: '10-Minute Full-Body Warmup', category: 'Daily Routine', videoId: 'c_KkG_LIf2E', thumbnail: 'https://i.ytimg.com/vi/c_KkG_LIf2E/hqdefault.jpg', duration: '10 min'},
    { id: 'dr4', title: '15 Min Daily Stretch (Full Body)', category: 'Daily Routine', videoId: 'L_xrDAtykMI', thumbnail: 'https://i.ytimg.com/vi/L_xrDAtykMI/hqdefault.jpg', duration: '15 min'},
    { id: 'dr5', title: '10 MIN MORNING STRETCH', category: 'Daily Routine', videoId: 'RelhI4h9w88', thumbnail: 'https://i.ytimg.com/vi/RelhI4h9w88/hqdefault.jpg', duration: '10 min'},
    { id: 'dr6', title: '15 MIN HAPPY MORNING WORKOUT', category: 'Daily Routine', videoId: 'FBnk_jG0-I8', thumbnail: 'https://i.ytimg.com/vi/FBnk_jG0-I8/hqdefault.jpg', duration: '15 min'},
    { id: 'dr7', title: '10 MIN WARM UP For Full Body Workouts', category: 'Daily Routine', videoId: 'CRl_f3m3x-Y', thumbnail: 'https://i.ytimg.com/vi/CRl_f3m3x-Y/hqdefault.jpg', duration: '10 min'},
    { id: 'dr8', title: '5min Daily Stretch for Flexibility', category: 'Daily Routine', videoId: '5-9d3Qk0a0w', thumbnail: 'https://i.ytimg.com/vi/5-9d3Qk0a0w/hqdefault.jpg', duration: '5 min'},
    { id: 'dr9', title: '5 Minute Move | Morning Stretch', category: 'Daily Routine', videoId: 'Y9N2_8m2_1A', thumbnail: 'https://i.ytimg.com/vi/Y9N2_8m2_1A/hqdefault.jpg', duration: '5 min'},
    { id: 'dr10', title: '15 Min Morning Workout to Start Your Day', category: 'Daily Routine', videoId: '2p_0_WdHy0A', thumbnail: 'https://i.ytimg.com/vi/2p_0_WdHy0A/hqdefault.jpg', duration: '15 min'},
    { id: 'dr11', title: '10 min Bedtime Stretch', category: 'Daily Routine', videoId: 'Zd2-p_F437c', thumbnail: 'https://i.ytimg.com/vi/Zd2-p_F437c/hqdefault.jpg', duration: '10 min'},
    { id: 'dr12', title: '5-Minute Cooldown Stretches', category: 'Daily Routine', videoId: 's2_y8_vmlMA', thumbnail: 'https://i.ytimg.com/vi/s2_y8_vmlMA/hqdefault.jpg', duration: '5 min'},
    { id: 'dr13', title: '10 Min Standing Abs', category: 'Daily Routine', videoId: 'Yd0jeIp3u4o', thumbnail: 'https://i.ytimg.com/vi/Yd0jeIp3u4o/hqdefault.jpg', duration: '10 min'},
    { id: 'dr14', title: 'Yoga For Beginners - The Basics', category: 'Daily Routine', videoId: 'v7AYKMP6rOE', thumbnail: 'https://i.ytimg.com/vi/v7AYKMP6rOE/hqdefault.jpg', duration: '20 min'},
    { id: 'dr15', title: '10 MIN GOOD MORNING WORKOUT', category: 'Daily Routine', videoId: 'g_uu89_wrlo', thumbnail: 'https://i.ytimg.com/vi/g_uu89_wrlo/hqdefault.jpg', duration: '10 min'},
    { id: 'dr16', title: '10 MIN FULL BODY STRETCH', category: 'Daily Routine', videoId: 'E1Y4n5L4i0Y', thumbnail: 'https://i.ytimg.com/vi/E1Y4n5L4i0Y/hqdefault.jpg', duration: '10 min'},
    { id: 'dr17', title: '10-Minute Home Workout For Seniors', category: 'Daily Routine', videoId: 'A2wp8Ipxn9s', thumbnail: 'https://i.ytimg.com/vi/A2wp8Ipxn9s/hqdefault.jpg', duration: '10 min'},
    { id: 'dr18', title: '15 MIN FULL BODY STRETCHING', category: 'Daily Routine', videoId: 'G1b_Qv_23_k', thumbnail: 'https://i.ytimg.com/vi/G1b_Qv_23_k/hqdefault.jpg', duration: '20 min'},
    { id: 'dr19', title: '10 Mins Daily Stretch', category: 'Daily Routine', videoId: 'Dr_iOc32D_k', thumbnail: 'https://i.ytimg.com/vi/Dr_iOc32D_k/hqdefault.jpg', duration: '10 min'},
    { id: 'dr20', title: '7-Minute Bedtime Yoga', category: 'Daily Routine', videoId: 'Li_T_h22I3E', thumbnail: 'https://i.ytimg.com/vi/Li_T_h22I3E/hqdefault.jpg', duration: '7 min'},

    // Strength (20+ videos)
    { id: 'str1', title: '30 MIN FULL BODY Dumbbell Workout', category: 'Strength', videoId: 'it_ZIs0_I_8', thumbnail: 'https://i.ytimg.com/vi/it_ZIs0_I_8/hqdefault.jpg', duration: '30 min'},
    { id: 'str2', title: '30-Minute Full Body DUMBBELL Workout', category: 'Strength', videoId: '0o2PwsgsYyw', thumbnail: 'https://i.ytimg.com/vi/0o2PwsgsYyw/hqdefault.jpg', duration: '30 min'},
    { id: 'str3', title: '20 min FULL BODY workout (Dumbbells)', category: 'Strength', videoId: '5pMF6x-48-A', thumbnail: 'https://i.ytimg.com/vi/5pMF6x-48-A/hqdefault.jpg', duration: '20 min'},
    { id: 'str4', title: '30-Min No-Equipment Strength Workout', category: 'Strength', videoId: 'JeejZ0-c-jU', thumbnail: 'https://i.ytimg.com/vi/JeejZ0-c-jU/hqdefault.jpg', duration: '30 min'},
    { id: 'str5', title: '20 MIN FULL BODY WORKOUT - With Dumbbells', category: 'Strength', videoId: 'JyV7mTYr4Sg', thumbnail: 'https://i.ytimg.com/vi/JyV7mTYr4Sg/hqdefault.jpg', duration: '20 min'},
    { id: 'str6', title: '30-Min Feel-Good Strength and Cardio', category: 'Strength', videoId: '50kH47ZztHs', thumbnail: 'https://i.ytimg.com/vi/50kH47ZztHs/hqdefault.jpg', duration: '30 min'},
    { id: 'str7', title: '30 MIN FULL BODY DUMBBELL WORKOUT', category: 'Strength', videoId: '3sE5jcAlFSI', thumbnail: 'https://i.ytimg.com/vi/3sE5jcAlFSI/hqdefault.jpg', duration: '30 min'},
    { id: 'str8', title: '30 Minute Full Body Dumbbell Workout', category: 'Strength', videoId: 'I7r2P_Ie39I', thumbnail: 'https://i.ytimg.com/vi/I7r2P_Ie39I/hqdefault.jpg', duration: '30 min'},
    { id: 'str9', title: '20 MIN DUMBBELL ARM WORKOUT', category: 'Strength', videoId: 'skde8_aSLi0', thumbnail: 'https://i.ytimg.com/vi/skde8_aSLi0/hqdefault.jpg', duration: '20 min'},
    { id: 'str10', title: '20 Min LEG WORKOUT (Dumbbells)', category: 'Strength', videoId: 'o_whYmILGFY', thumbnail: 'https://i.ytimg.com/vi/o_whYmILGFY/hqdefault.jpg', duration: '20 min'},
    { id: 'str11', title: '15 min Dumbbell ARM WORKOUT', category: 'Strength', videoId: 'KzZILhT_YqA', thumbnail: 'https://i.ytimg.com/vi/KzZILhT_YqA/hqdefault.jpg', duration: '15 min'},
    { id: 'str12', title: '30-Min Bodyweight Workout for Strength', category: 'Strength', videoId: 'E04dY91a534', thumbnail: 'https://i.ytimg.com/vi/E04dY91a534/hqdefault.jpg', duration: '30 min'},
    { id: 'str13', title: '15 MIN BOOTY WORKOUT with a Dumbbell', category: 'Strength', videoId: '6Lg50D_s1pA', thumbnail: 'https://i.ytimg.com/vi/6Lg50D_s1pA/hqdefault.jpg', duration: '15 min'},
    { id: 'str14', title: '15 Minute Full Body Dumbbell HIIT', category: 'Strength', videoId: 'l0gDqsSUtAo', thumbnail: 'https://i.ytimg.com/vi/l0gDqsSUtAo/hqdefault.jpg', duration: '15 min'},
    { id: 'str15', title: '45 Minute Full Body Dumbbell Workout', category: 'Strength', videoId: '5nZ452e-sS4', thumbnail: 'https://i.ytimg.com/vi/5nZ452e-sS4/hqdefault.jpg', duration: '45 min'},
    { id: 'str16', title: '30 MIN UNILATERAL Leg Workout', category: 'Strength', videoId: 'Zna_wz6tJ1A', thumbnail: 'https://i.ytimg.com/vi/Zna_wz6tJ1A/hqdefault.jpg', duration: '30 min'},
    { id: 'str17', title: '15 Minute Abs & Core Workout', category: 'Strength', videoId: 'kBROvo08yvA', thumbnail: 'https://i.ytimg.com/vi/kBROvo08yvA/hqdefault.jpg', duration: '15 min'},
    { id: 'str18', title: '20 min UPPER BODY workout (Dumbbells)', category: 'Strength', videoId: 'U-dwTAnS-3c', thumbnail: 'https://i.ytimg.com/vi/U-dwTAnS-3c/hqdefault.jpg', duration: '20 min'},
    { id: 'str19', title: '20 MIN LEG & BOOTY SHAPER (Dumbbells)', category: 'Strength', videoId: 'NRg1o0p_Gz8', thumbnail: 'https://i.ytimg.com/vi/NRg1o0p_Gz8/hqdefault.jpg', duration: '20 min'},
    { id: 'str20', title: '10 MIN SIXPACK WORKOUT // No Equipment', category: 'Strength', videoId: '8PwoytUU06g', thumbnail: 'https://i.ytimg.com/vi/8PwoytUU06g/hqdefault.jpg', duration: '10 min'},

    // Yoga (20+ videos)
    { id: 'yoga1', title: 'Yoga For Complete Beginners', category: 'Yoga', videoId: 'v7AYKMP6rOE', thumbnail: 'https://i.ytimg.com/vi/v7AYKMP6rOE/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga2', title: 'Total Body Yoga - Deep Stretch', category: 'Yoga', videoId: 'GLy2rYHwUqY', thumbnail: 'https://i.ytimg.com/vi/GLy2rYHwUqY/hqdefault.jpg', duration: '45 min'},
    { id: 'yoga3', title: 'Yoga For Anxiety and Stress', category: 'Yoga', videoId: 'hJbRpHq_dO0', thumbnail: 'https://i.ytimg.com/vi/hJbRpHq_dO0/hqdefault.jpg', duration: '28 min'},
    { id: 'yoga4', title: 'Yoga For Back Pain', category: 'Yoga', videoId: 'phuS5P1_Kxc', thumbnail: 'https://i.ytimg.com/vi/phuS5P1_Kxc/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga5', title: '30-Minute Power Yoga Flow', category: 'Yoga', videoId: 'R-4Li2C_1cM', thumbnail: 'https://i.ytimg.com/vi/R-4Li2C_1cM/hqdefault.jpg', duration: '30 min'},
    { id: 'yoga6', title: '20 Minute Yoga for Flexibility', category: 'Yoga', videoId: '4141-j_b-2Y', thumbnail: 'https://i.ytimg.com/vi/4141-j_b-2Y/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga7', title: '20-Minute Vinyasa Flow For Beginners', category: 'Yoga', videoId: 'b1H5b25t-2M', thumbnail: 'https://i.ytimg.com/vi/b1H5b25t-2M/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga8', title: '30-Min Power Yoga For Strength', category: 'Yoga', videoId: 'Eml2xnoLpYE', thumbnail: 'https://i.ytimg.com/vi/Eml2xnoLpYE/hqdefault.jpg', duration: '30 min'},
    { id: 'yoga9', title: '10 Minute Morning Yoga Full Body Stretch', category: 'Yoga', videoId: 'i_S-c-C-D8M', thumbnail: 'https://i.ytimg.com/vi/i_S-c-C-D8M/hqdefault.jpg', duration: '10 min'},
    { id: 'yoga10', title: '15-Minute Yoga for Core Strength', category: 'Yoga', videoId: 'e-_431pW_oA', thumbnail: 'https://i.ytimg.com/vi/e-_431pW_oA/hqdefault.jpg', duration: '15 min'},
    { id: 'yoga11', title: 'Yoga To Feel Your Best', category: 'Yoga', videoId: 't2n8-J-fRS4', thumbnail: 'https://i.ytimg.com/vi/t2n8-J-fRS4/hqdefault.jpg', duration: '30 min'},
    { id: 'yoga12', title: '20 min Evening Yoga Stretch for Sleep', category: 'Yoga', videoId: 'G7pMhQdCTe4', thumbnail: 'https://i.ytimg.com/vi/G7pMhQdCTe4/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga13', title: '45 Minute Intermediate Vinyasa Flow', category: 'Yoga', videoId: 'kFzJTa3t450', thumbnail: 'https://i.ytimg.com/vi/kFzJTa3t450/hqdefault.jpg', duration: '45 min'},
    { id: 'yoga14', title: 'Yin Yoga for Deep Relaxation', category: 'Yoga', videoId: 'Wk2n5-Y-afA', thumbnail: 'https://i.ytimg.com/vi/Wk2n5-Y-afA/hqdefault.jpg', duration: '30 min'},
    { id: 'yoga15', title: '30-Minute Yoga for Hips & Lower Back', category: 'Yoga', videoId: 'Ev2Vslg-n2w', thumbnail: 'https://i.ytimg.com/vi/Ev2Vslg-n2w/hqdefault.jpg', duration: '30 min'},
    { id: 'yoga16', title: 'Advanced Power Yoga Class', category: 'Yoga', videoId: '683G-t0e238', thumbnail: 'https://i.ytimg.com/vi/683G-t0e238/hqdefault.jpg', duration: '60 min'},
    { id: 'yoga17', title: 'Yoga for Neck & Shoulders (10 Min)', category: 'Yoga', videoId: 'X3-gKPN-APA', thumbnail: 'https://i.ytimg.com/vi/X3-gKPN-APA/hqdefault.jpg', duration: '10 min'},
    { id: 'yoga18', title: '20-Minute Yoga Workout to De-Stress', category: 'Yoga', videoId: 'pGOks-3DGMY', thumbnail: 'https://i.ytimg.com/vi/pGOks-3DGMY/hqdefault.jpg', duration: '20 min'},
    { id: 'yoga19', title: '15 Minute Feel Good Yoga Flow', category: 'Yoga', videoId: 'kF-w5c_es-g', thumbnail: 'https://i.ytimg.com/vi/kF-w5c_es-g/hqdefault.jpg', duration: '15 min'},
    { id: 'yoga20', title: 'Beginners Full Body At Home Yoga', category: 'Yoga', videoId: 'M-8FvC3GD8c', thumbnail: 'https://i.ytimg.com/vi/M-8FvC3GD8c/hqdefault.jpg', duration: '20 min'},

    // HIIT (20+ videos)
    { id: 'hiit1', title: '30-Minute No-Equipment HIIT Workout', category: 'HIIT', videoId: 'ml6cT4AZdqI', thumbnail: 'https://i.ytimg.com/vi/ml6cT4AZdqI/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit2', title: '30 Minute HIIT Workout // No Equipment', category: 'HIIT', videoId: 'PSGF5-3Jv8U', thumbnail: 'https://i.ytimg.com/vi/PSGF5-3Jv8U/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit3', title: '15 MIN BEGINNER HIIT WORKOUT', category: 'HIIT', videoId: 'gC_L9qAHVJ8', thumbnail: 'https://i.ytimg.com/vi/gC_L9qAHVJ8/hqdefault.jpg', duration: '15 min'},
    { id: 'hiit4', title: '20 MIN FULL BODY HIIT | No Equipment', category: 'HIIT', videoId: 'u-I0-s4Tj50', thumbnail: 'https://i.ytimg.com/vi/u-I0-s4Tj50/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit5', title: '30-Minute HIIT Cardio Workout', category: 'HIIT', videoId: 'NlPlya_2Gno', thumbnail: 'https://i.ytimg.com/vi/NlPlya_2Gno/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit6', title: '20 MIN FULL BODY HIIT', category: 'HIIT', videoId: 'pBeV-2Y8s-Y', thumbnail: 'https://i.ytimg.com/vi/pBeV-2Y8s-Y/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit7', title: '30 MIN FAT BURNING HIIT WORKOUT', category: 'HIIT', videoId: '1z0-mbiZA-A', thumbnail: 'https://i.ytimg.com/vi/1z0-mbiZA-A/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit8', title: '20 Mins HIIT Workout At Home', category: 'HIIT', videoId: 'RyfeTfg4_SA', thumbnail: 'https://i.ytimg.com/vi/RyfeTfg4_SA/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit9', title: '15 Minute Full Body HIIT Workout', category: 'HIIT', videoId: 'mEl2-i8TfqY', thumbnail: 'https://i.ytimg.com/vi/mEl2-i8TfqY/hqdefault.jpg', duration: '15 min'},
    { id: 'hiit10', title: '20 Minute LOW IMPACT HIIT', category: 'HIIT', videoId: 's-IV-3_J5L4', thumbnail: 'https://i.ytimg.com/vi/s-IV-3_J5L4/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit11', title: '30 MIN NO REPEAT HIIT WORKOUT', category: 'HIIT', videoId: '_khr_T2iISY', thumbnail: 'https://i.ytimg.com/vi/_khr_T2iISY/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit12', title: '15 MIN INTENSE HIIT | No Equipment', category: 'HIIT', videoId: 'nEa3I9f0v8g', thumbnail: 'https://i.ytimg.com/vi/nEa3I9f0v8g/hqdefault.jpg', duration: '15 min'},
    { id: 'hiit13', title: '10-Minute No-Equipment HIIT Workout', category: 'HIIT', videoId: 'Y-AlTmAte_I', thumbnail: 'https://i.ytimg.com/vi/Y-AlTmAte_I/hqdefault.jpg', duration: '10 min'},
    { id: 'hiit14', title: '15 MIN SEXY DANCE HIIT - Sweaty & Fun', category: 'HIIT', videoId: 'U8-aFEyL76A', thumbnail: 'https://i.ytimg.com/vi/U8-aFEyL76A/hqdefault.jpg', duration: '15 min'},
    { id: 'hiit15', title: '45 MIN NO REPEAT - Full Body HIIT', category: 'HIIT', videoId: 'j-t0-jOh-6E', thumbnail: 'https://i.ytimg.com/vi/j-t0-jOh-6E/hqdefault.jpg', duration: '45 min'},
    { id: 'hiit16', title: '30 Min No Equipment HIIT Cardio', category: 'HIIT', videoId: 'Ypo-6sm2tSg', thumbnail: 'https://i.ytimg.com/vi/Ypo-6sm2tSg/hqdefault.jpg', duration: '30 min'},
    { id: 'hiit17', title: '20 Minute Dumbbell HIIT Workout', category: 'HIIT', videoId: '44-32u5Rj1g', thumbnail: 'https://i.ytimg.com/vi/44-32u5Rj1g/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit18', title: '40 MIN BRUTAL HIIT WORKOUT', category: 'HIIT', videoId: 'zpe2_v0-L0E', thumbnail: 'https://i.ytimg.com/vi/zpe2_v0-L0E/hqdefault.jpg', duration: '40 min'},
    { id: 'hiit19', title: '20 min APARTMENT FRIENDLY HIIT', category: 'HIIT', videoId: 'bneSg-Nfg9s', thumbnail: 'https://i.ytimg.com/vi/bneSg-Nfg9s/hqdefault.jpg', duration: '20 min'},
    { id: 'hiit20', title: '30 MIN GLUTE HIIT with Dumbbells', category: 'HIIT', videoId: '3i-c7a-zWzE', thumbnail: 'https://i.ytimg.com/vi/3i-c7a-zWzE/hqdefault.jpg', duration: '30 min'},

    // Cardio (20+ videos)
    { id: 'cardio1', title: '30 MIN DANCE PARTY WORKOUT', category: 'Cardio', videoId: 'A1-cAzXiI4U', thumbnail: 'https://i.ytimg.com/vi/A1-cAzXiI4U/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio2', title: '30-Minute Cardio Latin Dance Workout', category: 'Cardio', videoId: '8DZktowZo_k', thumbnail: 'https://i.ytimg.com/vi/8DZktowZo_k/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio3', title: '20 MIN LOW IMPACT CARDIO', category: 'Cardio', videoId: 'Wn6t_x-3A00', thumbnail: 'https://i.ytimg.com/vi/Wn6t_x-3A00/hqdefault.jpg', duration: '20 min'},
    { id: 'cardio4', title: '30 Minute NO JUMPING CARDIO WORKOUT', category: 'Cardio', videoId: 'enYITYwv-DE', thumbnail: 'https://i.ytimg.com/vi/enYITYwv-DE/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio5', title: '20 MIN FUN & EFFECTIVE WORKOUT', category: 'Cardio', videoId: 'jpIz_zHle1U', thumbnail: 'https://i.ytimg.com/vi/jpIz_zHle1U/hqdefault.jpg', duration: '20 min'},
    { id: 'cardio6', title: '30 MIN FUN DANCE WORKOUT', category: 'Cardio', videoId: 'j5-s0pPA-UU', thumbnail: 'https://i.ytimg.com/vi/j5-s0pPA-UU/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio7', title: '20 MIN 2000s DANCE WORKOUT', category: 'Cardio', videoId: '4tavtV-522c', thumbnail: 'https://i.ytimg.com/vi/4tavtV-522c/hqdefault.jpg', duration: '20 min'},
    { id: 'cardio8', title: '30-Min No-Equipment Cardio & HIIT', category: 'Cardio', videoId: '8JpKOczCPJA', thumbnail: 'https://i.ytimg.com/vi/8JpKOczCPJA/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio9', title: '15 Minute Low Impact Beginner Cardio', category: 'Cardio', videoId: 'f0yXlRmw2Q0', thumbnail: 'https://i.ytimg.com/vi/f0yXlRmw2Q0/hqdefault.jpg', duration: '15 min'},
    { id: 'cardio10', title: '25 Minute FUN CARDIO WORKOUT', category: 'Cardio', videoId: 'T4s_yS__-B8', thumbnail: 'https://i.ytimg.com/vi/T4s_yS__-B8/hqdefault.jpg', duration: '25 min'},
    { id: 'cardio11', title: 'Fat Burning Cardio Warm Up', category: 'Cardio', videoId: '12-x0wOfi1Q', thumbnail: 'https://i.ytimg.com/vi/12-x0wOfi1Q/hqdefault.jpg', duration: '10 min'},
    { id: 'cardio12', title: '30 MIN 2000\'s DANCE HIIT WORKOUT', category: 'Cardio', videoId: 'H3jJ29oE8Zg', thumbnail: 'https://i.ytimg.com/vi/H3jJ29oE8Zg/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio13', title: '15 MIN NO JUMPING CARDIO', category: 'Cardio', videoId: 'L-tAhw0QdoA', thumbnail: 'https://i.ytimg.com/vi/L-tAhw0QdoA/hqdefault.jpg', duration: '15 min'},
    { id: 'cardio14', title: '20-Minute Standing Cardio Workout', category: 'Cardio', videoId: 'n2k-I-_a4_o', thumbnail: 'https://i.ytimg.com/vi/n2k-I-_a4_o/hqdefault.jpg', duration: '20 min'},
    { id: 'cardio15', title: '30-Minute Calorie Killer Cardio', category: 'Cardio', videoId: 'F4o4da0_QyM', thumbnail: 'https://i.ytimg.com/vi/F4o4da0_QyM/hqdefault.jpg', duration: '30 min'},
    { id: 'cardio16', title: '15 MIN HAPPY SWEAT - Let\'s Dance!', category: 'Cardio', videoId: 'IT94sLg-y_A', thumbnail: 'https://i.ytimg.com/vi/IT94sLg-y_A/hqdefault.jpg', duration: '15 min'},
    { id: 'cardio17', title: '20 MIN SWEATY CARDIO | No Equipment', category: 'Cardio', videoId: 'zW-f9Mv1L3Y', thumbnail: 'https://i.ytimg.com/vi/zW-f9Mv1L3Y/hqdefault.jpg', duration: '20 min'},
    { id: 'cardio18', title: '1 Hour NO REPEAT Cardio + Abs', category: 'Cardio', videoId: 'E4-g4__6AQA', thumbnail: 'https://i.ytimg.com/vi/E4-g4__6AQA/hqdefault.jpg', duration: '60 min'},
    { id: 'cardio19', title: '10 MIN QUICK CARDIO - No Equipment', category: 'Cardio', videoId: 'jpl73k_i_Lg', thumbnail: 'https://i.ytimg.com/vi/jpl73k_i_Lg/hqdefault.jpg', duration: '10 min'},
    { id: 'cardio20', title: '30-Min Feel-Good Strength and Cardio', category: 'Cardio', videoId: '50kH47ZztHs', thumbnail: 'https://i.ytimg.com/vi/50kH47ZztHs/hqdefault.jpg', duration: '30 min'},
];